# Generated by Django 4.2.3 on 2023-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('average_price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('coin_id', models.TextField()),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.TextField()),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.TextField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('coin_id', models.TextField()),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
